export type IconType =
  | 'arrow-right'
  | 'chevron-down'
  | 'search'
  | 'close'
  | 'hamburger'
  | 'chevron-left'
  | 'chevron-right'
  | 'double-chevron-left'
  | 'double-chevron-right'
  | 'arrow-left'
  | 'youtube'
  | 'telegram'
  | 'check'
  | 'person'
  | 'phone'
  | 'website'
