import { getNavigationData } from '@/lib/api/fetchNavigation'
import { getSocials } from '@/lib/api/fetchSocials'
import { cn } from '@/lib/utils/cn'
import { Footer, Header, Layout } from '@/ui/components'
import type { Metadata } from 'next'
import { Roboto_Mono, Roboto_Slab } from 'next/font/google'

import './globals.css'

const robotoSlab = Roboto_Slab({
  variable: '--font-roboto-slab',
  subsets: ['latin', 'cyrillic'],
})

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const navigationData = await getNavigationData()
  const socials = await getSocials()
  const transformedNavigationData = navigationData.map((item) => {
    return {
      ...item,
      isActive: false,
    }
  })

  const headerData = transformedNavigationData.filter(
    (item) => item.showInHeader,
  )
  const footerData = transformedNavigationData.filter(
    (item) => item.showInFooter,
  )
  return (
    <html lang='en'>
      <body
        className={cn(
          robotoSlab.variable,
          robotoMono.variable,
          'overflow-x-hidden antialiased',
        )}
      >
        <Header headerData={headerData} />
        <Layout>{children}</Layout>
        <Footer footerData={footerData} socials={socials} />
      </body>
    </html>
  )
}
