import { getHeaderData } from '@/lib/api/fetchHeader'
import { cn } from '@/lib/utils/cn'
import Header from '@/ui/Header/Header'
import type { Metadata } from 'next'
import { Roboto_Mono, Roboto_Slab } from 'next/font/google'

import './globals.css'

const robotoSlab = Roboto_Slab({
  variable: '--font-roboto-slab',
  subsets: ['latin', 'cyrillic'],
})

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headerData = await getHeaderData()
  return (
    <html lang='en'>
      <body
        className={cn(robotoSlab.variable, robotoMono.variable, 'antialiased')}
      >
        <Header headerData={headerData} />
        {children}
      </body>
    </html>
  )
}
